### ISSUE TITLE
Create README file with basic instructions

### ISSUE THREAD

**Issue by rmariuzzo** [jeanbernard/Calcula_Tu_Salario#1]
I would like to see a `README.md` file containing basic information on how to run the project, unit tests, how to contribute, etc...

**Comment by jeanbernard** [comment]
Hello! Thank you for taking an interest in the repo :]

I'll work on the README.md as soon as I can. In the meantime, all you need to do is clone the repo and open the .xcodeproj file in Xcode 7. 

A few caveats:
- I have yet to configure Travis CI however the tests can be run manually from inside Xcode. It'll even show you the current code coverage.
- Currently the project has to be run on the iPhone 6 or iPhone 6S simulator because I still need to set up Auto Layout for the other devices.
- I decided to use MVVM as opposed to the traditional MVC. For more info http://artsy.github.io/blog/2015/09/24/mvvm-in-swift/
- This is a pet project of mine for learning iOS development with Swift so things might not be...well....perfect😅.
